### ISSUE TITLE
Infinite Crash Loop

### ISSUE THREAD

**Issue by WilliamLCobb** [WilliamLCobb/iNDS#29]
I was unaware this was a thing. Has this happened to anyone else?
![img_0326](https://cloud.githubusercontent.com/assets/870904/12012972/5639ecfa-acd1-11e5-8edd-45b9c2a021d8.jpg)

**Comment by pmp174** [comment]
Ask them what device and ios version and whether it's jailbroken (some jailbreak tweaks affect multitasking) I haven't experienced this issue.

**Comment by OkazakiTheOtaku** [comment]
This has never happened to me. I compile with Xcode though, so it may not apply to me.

**Comment by brujo5** [comment]
No issue here tested in jalibroken and unjalibroken phones.

**Comment by WilliamLCobb** [comment]
I think it only happens when the app is downloaded from the build store. Maybe it's a problem on their end

**Comment by microbug** [comment]
Definitely happens to me (iOS 9.2, downloaded from build store). Very frustrating. When working, the app says its version 1.2.1 .

**Comment by WilliamLCobb** [comment]
It's either iOS 9.2 or Buildstore. Has anyone here tried building from source on iOS 9.2?

**Comment by Pepperoony** [comment]
I swear I'm able to use the app for a while only to later have it continually crash, and I can't tell what's triggering it. Sometimes it's when importing a new game from a rom website, other times I could just be playing to have the app crash and never open again, the only way to fix it is to delete and download again from the build store

I have an iPhone 6s and run iOS 9.2

**Comment by pmp174** [comment]
@Pepperoony did you download from builstore, cydia, or the source?

**Comment by pmp174** [comment]
@WilliamLCobb does the buildstore add advertisement to INDS?

**Comment by WilliamLCobb** [comment]
I downloaded from buildstore on iOS 9.0.2 and had no problems. So I think it's something with iOS 9.2. I'll try to borrow a friends phone tomorrow and see if I can figure it out.

**Comment by WilliamLCobb** [comment]
I don't think so. Why?

**Comment by pmp174** [comment]
I wanted to see because if they were adding ads to your code it could be messing with something.  I am running on 9.2.1 (beta) and haven't experienced this issue and I never experienced it while I was on 9.2.

**Comment by WilliamLCobb** [comment]
Do you have Dropbox sync enabled?

**Comment by pmp174** [comment]
I do on 9.2.1 but didn't on 9.2 since it wasn't available during that time.

**Comment by Pepperoony** [comment]
I downloaded the app from the buildstore

**Comment by Pepperoony** [comment]
It's happened four times, is there anything I could tell you that could help?

**Comment by WilliamLCobb** [comment]
It has to be something with the build store. I moved a bunch of things out of the main que at startup and I hope that will will fix it

**Comment by Pepperoony** [comment]
I'll redownload and try right now

**Comment by WilliamLCobb** [comment]
Not right now but I'll be releasing version 1.3.0 in a little bit. When they update it on the build store can you post here saying if it's fixed or now

**Comment by Pepperoony** [comment]
Sure sure, thanks

**Comment by pmp174** [comment]
it might be a signature problem , when a signature is revoked an app won't open. Idk if it causes looping but it could be a signature issue I mean that's really all they (buildstore) add is a different signature.

**Comment by WilliamLCobb** [comment]
I think build store does something different where they create a developer account with 100 test accounts that aren't revoked or something. 

I think the crashing he was referring to is just random crashing that is expected but not being able to open it back up makes no sense. If I had to guess something in the bundle is being overwritten as a result of the crash and when that happens it invalidates the signature and the app can't open until you redownload it. But I could be completely wrong

**Comment by pmp174** [comment]
Is there a way to get a crash log?

**Comment by WilliamLCobb** [comment]
I don't think it even produces a crash log when this happens. Which would explain why I've never received one. Hopefully it's not that though and the changes I made will fix it

**Comment by Pepperoony** [comment]
When will the latest update launch? The next couple of days?

**Comment by WilliamLCobb** [comment]
It's up on buildstore now

**Comment by Pepperoony** [comment]
I'll try it out and report if I get any crashes

**Comment by Pepperoony** [comment]
When exporting a rom zip file from another app into the iNDS app, it no longer saves to the app, like it doesn't appear in the main menu. And when exporting another time, the app crashed like it usually would, but this time thankfully I could open it again.

**Comment by WilliamLCobb** [comment]
Yea I messed up 7z in the last version by accident. It'll be fixed in the next version though

**Comment by Pepperoony** [comment]
Even worse I can't download roms from anywhere through the in-app browser making the app useless :/ it'll start to download and then stall on 'opening' and I'll try leaving the app then opening it again, and the file will just be gone

**Comment by microbug** [comment]
I updated to 1.3.0 via the build store. I am getting a random crash loop, but it's different this time. Like before, deleting the app and reinstalling fixed the problem, but (unlike before) transferring the old data to it didn't break it again. To clarify, once the crash loop started, I connected my phone to iTunes and transferred all the data from iNDS to my PC. I deleted and reinstalled it, and transferred the data back to iNDS and it works.

**Comment by WilliamLCobb** [comment]
Thank you so much for this! Could you possible zip that folder causing the problem and email it to me?

Sent from Outlook Mobile




On Fri, Jan 1, 2016 at 7:12 AM -0800, "Richard Coleman" <notifications@github.com> wrote:












I updated to 1.3.0 via the build store. I am getting a random crash loop, but it's different this time. Like before, deleting the app and reinstalling fixed the problem, but (unlike before) transferring the old data to it didn't break it again. To clarify, once the crash loop started, I connected my phone to iTunes and transferred all the data from iNDS to my PC. I deleted and reinstalled it, and transferred the data back to iNDS and it works.

**Comment by WilliamLCobb** [comment]
Are you saying this time it's not because of the data?

Sent from Outlook Mobile




On Fri, Jan 1, 2016 at 7:12 AM -0800, "Richard Coleman" <notifications@github.com> wrote:












I updated to 1.3.0 via the build store. I am getting a random crash loop, but it's different this time. Like before, deleting the app and reinstalling fixed the problem, but (unlike before) transferring the old data to it didn't break it again. To clarify, once the crash loop started, I connected my phone to iTunes and transferred all the data from iNDS to my PC. I deleted and reinstalled it, and transferred the data back to iNDS and it works.

**Comment by microbug** [comment]
It seems so; once I restored the data it didn't crash. I did have some weird issues with sound not playing though. I'll send you and anyone else who can contribute a link; I don't think it's a good idea to post it here since it contains ROMs.

**Comment by Pepperoony** [comment]
Any idea when audio will be as stable as the fps. I've noticed most music in games is a bit off, could be the roms themselves but I've noticed it in most games, specifically professor layton, whose voice acting is completely messed up

**Comment by brujo5** [comment]
That normal because the emulator uses fast forward to speed up emulation.(1x,2x,3x)

for that reason they are not synchronized sound and video. 
all this will be resolved in a future when JIT code is finalized. (time to time). I prefer better FPS than Audio. 
From nds4ios to inds of change has been immense. Thx

**Comment by WilliamLCobb** [comment]
Which games do you notice it most? I can use them to test it

**Comment by brujo5** [comment]
@ Pepperoony says
professor layton game

**Comment by Pepperoony** [comment]
I'm grateful the fps is constantly a rock solid 60 fps in every game I've played, I remember trying NDS4iOS a year ago and it was pretty much unplayable.

However the audio is just a little off, sometimes it's very easily forgettable. Such as the ace attorney games, everything sounds perfect but there's a few stutters in the music I can hear.

As I mentioned, Professor Layton and the Curious Village has voice acting that is quite ruined by the audio glitches. I turn on synchronous audio and that helps a lot, but ruins sound affects in other parts of the game, so I have to turn it off and on a lot.

What I'm describing is in the first five minutes of the game. So defiantly just give it a try @WilliamLCobb

**Comment by SE2Dev** [comment]
I've never even been able launch it on iOS 8.4 on a 5s - it just crashes at the splash screen.

**Comment by microbug** [comment]
Pokémon 4th gen music sounds very odd, especially without synchronous audio on. There are also graphical glitches in the form of black pixels on the screen, which move randomly when you move; this makes it unplayable for me.

**Comment by microbug** [comment]
I've worked out how to reproduce the crash bug I experienced before. I have two profiles with the same name, 'Pokémon'. When I try to delete them, the app crashes when I tap to get rid of the second one. If I try to reopen it crashes again, but just going to the build store and reinstalling it solves the problem (despite it being the same data). This is on 3.0.2 (thanks for the Taptic feedback BTW). Will send you the current zip of save files.

**Comment by microbug** [comment]
Oops, update: redownloading didn't fix it this time. Will send files.

**Comment by WilliamLCobb** [comment]
Thanks so much for this! The culprit is definitely Dropbox. I'll start working a on a replacement

**Comment by microbug** [comment]
Ok, great. I have noticed some odd things with Dropbox, e.g., sometimes if you click link but then cancel it the app pops up with 'linked successfully'.

**Comment by WilliamLCobb** [comment]
I think I fixed it! Thank you guys for all the help.

What was happening was when a file in the directory synced by dropbox was deleted, the dropbox manager deleted the file locally and then queued it to be deleted remotely. It then reloaded the remote file list and if the dropbox server responded quickly enough, it would say it still had that file. The dropbox sync library was dumb and thought since dropbox still had the file it must be new and it should be redownloaded. But once it tried to redownload it, dropbox freaked out because it was supposed to delete the file remotely but also download it back to the device. It then ends up panicking and just crashing the phone over and over again until you reset your local files by deleting and reinstalling the app.

Hopefully this will all be fixed now in the next version.

**Comment by Pepperoony** [comment]
Eta on the update?


--


Luke Rooney/ Manager of Marketing
luke.rooney@servitehs.org(mailto:luke_rooney@icloud.com)/(562)-360-4258(tel:(562)-360-4258)


Trinity Corporation
ServiteHS.org
1952 W La Palma Ave, Anaheim(x-apple-data-detectors://5/2)

**Comment by WilliamLCobb** [comment]
I'll try to get it out tonight or tomorrow morning. The build store will probably then release it tomorrow

**Comment by SlickNicky10** [comment]
I'm using iNDS on non-jailbroken iOS 9.2 from Buildstore and it was working great, until I enabled Dropbox sync. No matter what I tried (aside from restoring my iPhone) Dropbox syncing would start and crash the app. I even disconnected it and deleted the folder, still crashing. Please help!

**Comment by WilliamLCobb** [comment]
I'll take another look at the Dropbox sync code. Can you remember anything you did that started the crash loop?

**Comment by addirg** [comment]
Hey, I've downloaded the app from the build store as I've payed for that service but for some reason it's crashes every time I go to open it preventing me from even entering the app! Any help would be greatly appreciated!!

**Comment by cmmc38** [comment]
Hi, same issue here except had nothing to do with drop box. The app just stopped working after I tried to update it from the build store. Was a new version uploaded there recently?  Everytine I try to load it crashes.

**Comment by cmmc38** [comment]
Apologies for double post. I have contacted Build Sote support and I will let you know what they say.

**Comment by WilliamLCobb** [comment]
Should be fixed in 1.4.0. Please re open if iNDS still crashes on launch after updating.

**Comment by srijan5** [comment]
This has happened to me many many times, even today. I had to uninstall the app(downloaded from iemulators.com) and then reinstall it. After doing this i would sign in again to mu dropbox account, sync it, but it wouldnt load the file even when its there in my dropbox. Anyway it usually had a very old autosave with which i resumes playing but as of now there is no autosave file too. I tried everything but of no use and the game just starts from the beginning.... If you need any more information, just type it here and i'll provide it to you.
Btw as someone said it happens when you change between apps without closing iNDS but this time it happened as i was playing.

**Comment by WilliamLCobb** [comment]
What version are you using? You can find it in the very bottom of the settings

**Comment by srijan5** [comment]
1.4.0

**Comment by srijan5** [comment]
And btw, if these are .dsv saves do uk any means how i can restore my save file from my dropbox?

**Comment by WilliamLCobb** [comment]
There was a bug that caused a crash loop anytime iNDS crashed. iNDS 1.5.0 still crashes some but it won't enter the loop. Unfortunately if you downloaded from iEmulators, you'll have to wait for them to update the app on their website.

Dropbox saves all deleted files for 30 days. Here is how you can get them back: https://www.dropbox.com/en/help/296

**Comment by srijan5** [comment]
I dont know if this will help you in any way but when i reinstalled the app and opened it, it automatically made an autosave file in my dropbox which i deleted and put the older save in its place, but still the new auto save remained. Btw iNDS is sometimes showing sync failed

**Comment by srijan5** [comment]
The older save was never deleted! It is stillin the iNDS directory of my dropbox but for some unknown reason it is just not using the older save

**Comment by essiw** [comment]
Did you after checkin the synch with dropbox option reopen iNDS and wait untill it said "synching complete" it might be the case that it does not synch directly after checking the option, or that you did not wait long enough for it to synch completely. Either one will cause iNDS to think that there is no previous safe file, becuase it did not yet receive those save files.

**Comment by srijan5** [comment]
Yes i actually did wait for it but somehow it didnt happen

**Comment by SquareX3** [comment]
1.4.0
Still have problem.
and plz update newest version on iemulator.

**Comment by essiw** [comment]
^it is obvious that if you have 1.4.0 you would still have this problem... as the problem lies with version 1.4.0, furthermore WilliamLCobb has no influence on iemulators, so he cannot update the newest version on there, instead of asking that here, go ask iemulators instead.

**Comment by 12killa** [comment]
My always gives me the "unable to download" error... Is there anything I can do to fix that?

**Comment by essiw** [comment]
Go ask the website you are trying to download it from, this place cannot do that for you unless you downloaded it from github.

**Comment by benihana7** [comment]
I'm experiencing the infinite crash loop on version 1.5.4 downloaded from source (GitHub) and side loaded (not jail broken) on iPhone 6 iOS 9.3.3. I will try to remove and side-load again.
